# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "Installing dependencies"

  - script: npm run prettier
    displayName: "Checking format rules"

  - script: npm run lint
    displayName: "Checking lint rules"

  - script: npm run test
    displayName: "Checking unit tests"

  - script: npm run build
    displayName: "Building the app"
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/dist"
      skip_api_build: true
      skip_app_build: true
      azure_static_web_apps_api_token: "acfe9d063f4365cdc7487552cb99f41fb4af6cba616ffd83534dd6b7ff29f1ee4-fb608880-2928-4515-a149-b415fbbb556c003323016"
